@hostname=localhost
@port=3000
@host=http://{{hostname}}:{{port}}
@bearer_token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjb21wYW55aWQiOiI0ZmJiODA2My00NmQwLTRkY2UtYjBlOC05NTRlMDY5NGI0ODUiLCJlbWFpbCI6ImpvaG5AZW1haWwuY29tIiwiZXhwIjoxNzQ5ODExMzkyLCJ1c2VyaWQiOiJkZmU0NzlkOC1kMWJlLTQzNTUtOWM4Yi03NGUxNjAyYTJjMWYiLCJ1c2VybmFtZSI6IkpvaG5Eb2UifQ.DozJQRxTxzEp7lTFOZdLTdodR3QTH1qKhvxFk2l8ARI

### create company
POST {{host}}/company/create
Content-Type: application/json
Authorization: {{bearer_token}}

{
    "name": "Skinnende Badeplass"
}

### join company
POST {{host}}/company/join/4fbb8063-46d0-4dce-b0e8-954e0694b485
Content-Type: application/json
Authorization: {{bearer_token}}

